### ISSUE TITLE
gizmod unused but same error

### ISSUE THREAD

**Issue by kuh3h3** [MSchmoecker/CustomShips#1]
[LogOutput.log](https://github.com/MSchmoecker/CustomShips/files/13859066/LogOutput.log)

**Comment by MSchmoecker** [comment]
Can you try if it was fixed by 0.1.2?
The conflict was likely ValheimRaft in this case, Gizmo, ValheimRaft and CustomShips patch into the same method there and produce the same exception.

**Comment by MSchmoecker** [comment]
Fixed in 0.1.2. Otherwise please reopen the issue
